name: Sphinx build

on:
  push:
    branches:
    - master

jobs:
  update:

    environment: github-pages
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: | 
        sudo apt install pandoc
        python -m pip install --upgrade pip
        python -m pip install flake8
        pip install -r requirements.txt
        pip install -r test_requirements.txt
        pip install -r docs/requirements.txt
    - name: Build HTML
      run: |
        sphinx-apidoc citylearn -o docs/source/api -e -M
        sphinx-build -b html docs/source/ docs/build/html
    - name: Add CNAME
      run: |
        echo ${{ secrets.CUSTOM_DOMAIN }} > docs/build/html/CNAME
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html